apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - port: 80          # Internal cluster port
      targetPort: 3500  # Port inside the container
      nodePort: 30081   # External port (optional, fixed)
