services:
  nginx:
    image: vineetsaini13/frontend-image:latest
    ports:
      - 80:80
    networks:
        - three-tier-net

  backend:
      image: vineetsaini13/backend-image:latest
      ports:
        - 3500:3500
      networks:
        - three-tier-net
    
  db:
      image: mysql
      ports:
        - 3306:3306
      environment:
        - MYSQL_ROOT_PASSWORD=mysql123
        - MYSQL_DATABASE=school
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      networks:
        - three-tier-net
networks:
  three-tier-net:
    name: three-tier-net
    driver: bridge
